### ISSUE TITLE
Exception on Run

### ISSUE THREAD

**Issue by ktisha** [ktisha/TheRPlugin#8]
java.lang.Throwable: Must provide not-empty presentable name
	at com.intellij.util.io.BaseDataReader.start(BaseDataReader.java:50)
	at com.intellij.util.io.BaseDataReader.start(BaseDataReader.java:45)
	at com.jetbrains.ther.run.TheRXProcessHandler$TheRXBaseOutputReader.<init>(TheRXProcessHandler.java:239)
	at com.jetbrains.ther.run.TheRXProcessHandler.createOutputDataReader(TheRXProcessHandler.java:141)
	at com.intellij.execution.process.BaseOSProcessHandler$1.startNotified(BaseOSProcessHandler.java:116)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.execution.process.ProcessHandler$4.invoke(ProcessHandler.java:214)
	at com.sun.proxy.$Proxy14.startNotified(Unknown Source)
	at com.intellij.execution.process.ProcessHandler.startNotify(ProcessHandler.java:67)
	at com.intellij.execution.process.BaseOSProcessHandler.startNotify(BaseOSProcessHandler.java:145)
	at com.jetbrains.ther.run.TheRXProcessHandler.startNotify(TheRXProcessHandler.java:121)
	at com.intellij.execution.impl.ExecutionManagerImpl$5.run(ExecutionManagerImpl.java:391)
	at com.intellij.execution.impl.ExecutionManagerImpl.compileAndRun(ExecutionManagerImpl.java:289)
	at com.intellij.execution.impl.ExecutionManagerImpl.startRunProfile(ExecutionManagerImpl.java:419)
	at com.intellij.execution.runners.GenericProgramRunner.execute(GenericProgramRunner.java:40)
	at com.intellij.execution.runners.BaseProgramRunner.execute(BaseProgramRunner.java:61)
	at com.intellij.execution.runners.GenericProgramRunner.execute(GenericProgramRunner.java:31)
	at com.intellij.execution.runners.BaseProgramRunner.execute(BaseProgramRunner.java:50)
	at com.intellij.execution.runners.GenericProgramRunner.execute(GenericProgramRunner.java:31)
	at com.intellij.execution.ProgramRunnerUtil.executeConfiguration(ProgramRunnerUtil.java:94)
	at com.intellij.execution.impl.ExecutionManagerImpl.start(ExecutionManagerImpl.java:114)
	at com.intellij.execution.impl.ExecutionManagerImpl.access$400(ExecutionManagerImpl.java:65)
	at com.intellij.execution.impl.ExecutionManagerImpl$7.run(ExecutionManagerImpl.java:503)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:353)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:345)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:329)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:857)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:658)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by sproshev** [comment]
BaseDataReader.start(String) has been introduced in https://github.com/JetBrains/intellij-community/commit/1b28f8e2e60487d24bd0b2f0c792ec44a609bdff?diff=split#diff-9b0dbf6e4f68dffad1a2aa5c05ecd743 and is not available in 15.0.3 or earlier.

Usage will be updated later.

**Comment by sproshev** [comment]
Fixed in 6c925ee0a725f41f91c2ef7155b44cd044dfce0d
